In [20]:
# EE2211 Lecture 6 Demo 1 Binary classification
import numpy as np
from numpy.linalg import inv

X = np.array([[1,-7], [1,-5], [1,1], [1,5]])
y = np.array([[-1], [-1], [1], [1]])
## Linear regression for classification
w = inv(X.T @ X) @ X.T @ y
print("Estimated w")
print(w)
print("\n")              
              
Xt = np.array([[1,-2]])
y_predict = Xt @ w
print("Predicted y")
print(y_predict)
print("\n")           

y_class_predict = np.sign(y_predict)
print("Predicted y class")
print(y_class_predict)

Estimated w
[[0.2967033]
 [0.1978022]]


Predicted y
[[-0.0989011]]


Predicted y class
[[-1.]]


In [21]:

# EE2211 Lecture 6 Demo 2 Multi-class classification
import numpy as np
from numpy.linalg import inv
from sklearn.preprocessing import OneHotEncoder
X = np.array([[1, 1, 1], [1, -1, 1], [1, 1, 3], [1, 1, 0]])
y_class = np.array([[1], [2], [1], [3]])
y_onehot = np.array([[1, 0, 0], [0, 1, 0], [1, 0, 0], [0, 0, 1]])
print("One-hot encoding manual")
print(y_class)
print(y_onehot)
print("\n")              
              
print("One-hot encoding function")
onehot_encoder = OneHotEncoder(sparse=False)
print(onehot_encoder)
Ytr_onehot = onehot_encoder.fit_transform(y_class)
print(Ytr_onehot)


One-hot encoding manual
[[1]
 [2]
 [1]
 [3]]
[[1 0 0]
 [0 1 0]
 [1 0 0]
 [0 0 1]]


One-hot encoding function
OneHotEncoder(sparse=False)
[[1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]


In [25]:
## Linear Classification
print("Estimated W")
W = inv(X.T @ X) @ X.T @ Ytr_onehot
print(W)
X_test = np.array([[1, 0, -1]])
yt_est = X_test@W;
print("\n")
print("Test") 
print(yt_est)

#yt_class = [[1 if y == max(x) else 0 for y in x] for x in yt_est ] 
#print("\n")
#print("class label test")   
#print(yt_class)

print("\n")
print("Predicted class label test using argmax")   
print(np.argmax(yt_est)+1)

Estimated W
[[ 1.66533454e-16  5.00000000e-01  5.00000000e-01]
 [ 2.85714286e-01 -5.00000000e-01  2.14285714e-01]
 [ 2.85714286e-01  5.55111512e-17 -2.85714286e-01]]


Test
[[-0.28571429  0.5         0.78571429]]


Predicted class label test using argmax
3


In [26]:
#EE2211 Lecture 6 Demo 3 Polynomial regression
import numpy as np
from numpy.linalg import inv
from numpy.linalg import matrix_rank
from sklearn.preprocessing import PolynomialFeatures
X = np.array([[1, 1], [-1, 1], [1, -1], [-1, -1]])
y = np.array([[1], [-1], [-1], [1]])
## Generate polynomial features
order = 2
poly = PolynomialFeatures(order)
print(poly)
P = poly.fit_transform(X)
print("matrix P")
print(P)

print("***************************************")
#print(matrix_rank(P))
#PY = np.vstack((P.T, y.T))
#print(matrix_rank(PY.T))

## dual solution m < d (without ridge)
w_dual = P.T @ inv(P @ P.T) @ y
print("Under-determined system")
print("Unique constrained solution, no ridge")
print(w_dual)

print("***************************************")
print("Approximation with dual ridge regression")
print(P.shape)
reg_L2 = 0.0001*np.identity(P.shape[0]) #number of rows of P = Dual I
print(reg_L2)
w_dual_ridge = P.T @ (inv(P @ P.T + reg_L2)) @ y
print(w_dual_ridge)

print("***************************************")
## primal ridge 
print("Approximation with primal ridge regression")
print(P.shape)
reg_L = 0.0001*np.identity(P.shape[1]) #number of columns of P = Primal I
print(reg_L)
w_primal_ridge = inv(P.T @ P + reg_L) @ P.T @ y
print(w_primal_ridge)

PolynomialFeatures()
matrix P
[[ 1.  1.  1.  1.  1.  1.]
 [ 1. -1.  1.  1. -1.  1.]
 [ 1.  1. -1.  1. -1.  1.]
 [ 1. -1. -1.  1.  1.  1.]]
***************************************
Under-determined system
Unique constrained solution, no ridge
[[-4.16333634e-17]
 [-1.11022302e-16]
 [-5.55111512e-17]
 [-4.16333634e-17]
 [ 1.00000000e+00]
 [-4.16333634e-17]]
***************************************
Approximation with dual ridge regression
(4, 6)
[[0.0001 0.     0.     0.    ]
 [0.     0.0001 0.     0.    ]
 [0.     0.     0.0001 0.    ]
 [0.     0.     0.     0.0001]]
[[0.      ]
 [0.      ]
 [0.      ]
 [0.      ]
 [0.999975]
 [0.      ]]
***************************************
Approximation with primal ridge regression
(4, 6)
[[0.0001 0.     0.     0.     0.     0.    ]
 [0.     0.0001 0.     0.     0.     0.    ]
 [0.     0.     0.0001 0.     0.     0.    ]
 [0.     0.     0.     0.0001 0.     0.    ]
 [0.     0.     0.     0.     0.0001 0.    ]
 [0.     0.     0.     0.     0.     0.0001

In [28]:
#EE2211 Lecture 6 Demo 3 Training/Learning
import numpy as np
from numpy.linalg import inv
from numpy.linalg import matrix_rank
from sklearn.preprocessing import PolynomialFeatures
X = np.array([[1, 1], [-1, 1], [1, -1], [-1, -1]])
y = np.array([[1], [-1], [-1], [1]])
## Generate polynomial features
order = 2
poly = PolynomialFeatures(order)
print(poly)
P = poly.fit_transform(X)
print("matrix P")
print(P)
print("Under-determined system")
print(matrix_rank(P))
PY = np.vstack((P.T, y.T))
print(matrix_rank(PY.T))

## dual solution m < d (without ridge)
w_dual = P.T @ inv(P @ P.T) @ y
print("Unique constrained solution, no ridge")
print(w_dual)
#print(np.around(w_dual,3))

PolynomialFeatures()
matrix P
[[ 1.  1.  1.  1.  1.  1.]
 [ 1. -1.  1.  1. -1.  1.]
 [ 1.  1. -1.  1. -1.  1.]
 [ 1. -1. -1.  1.  1.  1.]]
Under-determined system
4
4
Unique constrained solution, no ridge
[[-4.16333634e-17]
 [-1.11022302e-16]
 [-5.55111512e-17]
 [-4.16333634e-17]
 [ 1.00000000e+00]
 [-4.16333634e-17]]


In [30]:
#testing

Xnew= np.array([ [0.2, 0.5]])
# Two test points
#Xnew= np.array([ [0.2, 0.5], [-0.9, 0.7]])
Pnew = poly.fit_transform(Xnew)
print(Xnew)
print(Pnew)


print("Prediction")
Ynew=Pnew@w_dual
print(Ynew)
print(np.sign(Ynew))

[[0.2 0.5]]
[[1.   0.2  0.5  0.04 0.1  0.25]]
Prediction
[[0.1]]
[[1.]]
